
package com.ejie.af20a.integracion.gestorInterconsulta.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GestorInterconsultaWebServiceImpl", targetNamespace = "http://ejie.com/af20a.integracion.gestorInterconsulta.webservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GestorInterconsultaWebServiceImpl {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.ejie.af20a.integracion.gestorInterconsulta.webservice.client.RealizarInterconsultaResponse
     */
    @WebMethod
    @WebResult(name = "realizarInterconsultaResponse", targetNamespace = "http://ejie.com/af20a.integracion.gestorInterconsulta.webservice", partName = "parameters")
    public RealizarInterconsultaResponse realizarInterconsulta(
        @WebParam(name = "realizarInterconsultaRequest", targetNamespace = "http://ejie.com/af20a.integracion.gestorInterconsulta.webservice", partName = "parameters")
        RealizarInterconsultaRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ejie.af20a.integracion.gestorInterconsulta.webservice.client.RespuestaIdentificacionResponse
     */
    @WebMethod
    @WebResult(name = "respuestaIdentificacionResponse", targetNamespace = "http://ejie.com/af20a.integracion.gestorInterconsulta.webservice", partName = "parameters")
    public RespuestaIdentificacionResponse respuestaIdentificacion(
        @WebParam(name = "respuestaIdentificacionRequest", targetNamespace = "http://ejie.com/af20a.integracion.gestorInterconsulta.webservice", partName = "parameters")
        RespuestaIdentificacionRequestWrapper parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ejie.af20a.integracion.gestorInterconsulta.webservice.client.RespuestaConsultaResponse
     */
    @WebMethod
    @WebResult(name = "respuestaConsultaResponse", targetNamespace = "http://ejie.com/af20a.integracion.gestorInterconsulta.webservice", partName = "parameters")
    public RespuestaConsultaResponse respuestaConsulta(
        @WebParam(name = "respuestaConsultaRequest", targetNamespace = "http://ejie.com/af20a.integracion.gestorInterconsulta.webservice", partName = "parameters")
        RespuestaConsultaRequestWrapper parameters);

}
