
package com.ejie.af20a.integracion.gestorInterconsulta.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "gestorInterconsultaWebService", targetNamespace = "http://ejie.com/af20a.integracion.gestorInterconsulta.webservice", wsdlLocation = "https://svc.integracion.des.ejgv.jaso/ctxweb/secured_ssl/AF20AGestorInterconsulta?wsdl")
public class GestorInterconsultaWebService
    extends Service
{

    private final static URL GESTORINTERCONSULTAWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException GESTORINTERCONSULTAWEBSERVICE_EXCEPTION;
    private final static QName GESTORINTERCONSULTAWEBSERVICE_QNAME = new QName("http://ejie.com/af20a.integracion.gestorInterconsulta.webservice", "gestorInterconsultaWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://svc.integracion.des.ejgv.jaso/ctxweb/secured_ssl/AF20AGestorInterconsulta?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GESTORINTERCONSULTAWEBSERVICE_WSDL_LOCATION = url;
        GESTORINTERCONSULTAWEBSERVICE_EXCEPTION = e;
    }

    public GestorInterconsultaWebService() {
        super(__getWsdlLocation(), GESTORINTERCONSULTAWEBSERVICE_QNAME);
    }

    public GestorInterconsultaWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GESTORINTERCONSULTAWEBSERVICE_QNAME, features);
    }

    public GestorInterconsultaWebService(URL wsdlLocation) {
        super(wsdlLocation, GESTORINTERCONSULTAWEBSERVICE_QNAME);
    }

    public GestorInterconsultaWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GESTORINTERCONSULTAWEBSERVICE_QNAME, features);
    }

    public GestorInterconsultaWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestorInterconsultaWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GestorInterconsultaWebServiceImpl
     */
    @WebEndpoint(name = "gestorInterconsultaWebServicePort")
    public GestorInterconsultaWebServiceImpl getGestorInterconsultaWebServicePort() {
        return super.getPort(new QName("http://ejie.com/af20a.integracion.gestorInterconsulta.webservice", "gestorInterconsultaWebServicePort"), GestorInterconsultaWebServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestorInterconsultaWebServiceImpl
     */
    @WebEndpoint(name = "gestorInterconsultaWebServicePort")
    public GestorInterconsultaWebServiceImpl getGestorInterconsultaWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ejie.com/af20a.integracion.gestorInterconsulta.webservice", "gestorInterconsultaWebServicePort"), GestorInterconsultaWebServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GESTORINTERCONSULTAWEBSERVICE_EXCEPTION!= null) {
            throw GESTORINTERCONSULTAWEBSERVICE_EXCEPTION;
        }
        return GESTORINTERCONSULTAWEBSERVICE_WSDL_LOCATION;
    }

}
